// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjsjkhzmphscralfmzmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqc2praHptcGhzY3JhbGZtem1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTE2NDYsImV4cCI6MjA2NzAyNzY0Nn0.TX3lj0_bzSYk0iVjb03OoJlsV_mB5MrGhuxrXdfZfXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});